# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from grille import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1110, 878)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 140, 731, 661))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid.setContentsMargins(0, 0, 0, 0)
        self.grid.setObjectName("grid")
        self.title_text = QtWidgets.QPlainTextEdit(Dialog)
        self.title_text.setGeometry(QtCore.QRect(40, 20, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.title_text.setFont(font)
        self.title_text.setAutoFillBackground(True)
        self.title_text.setObjectName("title_text")
        self.difficulty_box_choice = QtWidgets.QComboBox(Dialog)
        self.difficulty_box_choice.setGeometry(QtCore.QRect(140, 90, 151, 22))
        self.difficulty_box_choice.setObjectName("difficulty_box_choice")
        self.difficulty_text = QtWidgets.QPlainTextEdit(Dialog)
        self.difficulty_text.setGeometry(QtCore.QRect(40, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.difficulty_text.setFont(font)
        self.difficulty_text.setAutoFillBackground(True)
        self.difficulty_text.setObjectName("difficulty_text")
        self.button_validate_difficulty = QtWidgets.QPushButton(Dialog)
        self.button_validate_difficulty.setGeometry(QtCore.QRect(300, 90, 31, 23))
        self.button_validate_difficulty.setObjectName("button_validate_difficulty")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_text.setPlainText(_translate("Dialog", "Minesweeper Game"))
        self.difficulty_text.setPlainText(_translate("Dialog", "Difficulté :"))
        self.button_validate_difficulty.setText(_translate("Dialog", "OK"))

class Window(QtWidgets.QMainWindow):
    def __init__(self):
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.comboBox.addItem("Facile")
        self.ui.comboBox.addItem("Moyen")
        self.ui.comboBox.addItem("Difficile")
    
if __name__=="__main__":
    app = QtWidgets.QApplication([])
    application = Window()
    sys.exit(app.exec())
        
        