# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import sys
from grille import Grille, CaseBombe, CaseVide


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1110, 878)
        
        # Zone Grille
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 140, 731, 661))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid.setContentsMargins(0, 0, 0, 0)
        self.grid.setSpacing(2)
        self.grid.setObjectName("grid")
        
        # Zone titre
        self.title_text = QtWidgets.QPlainTextEdit(Dialog)
        self.title_text.setGeometry(QtCore.QRect(40, 20, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.title_text.setFont(font)
        self.title_text.setAutoFillBackground(True)
        self.title_text.setObjectName("title_text")
        
        ### Boite de difficulté
        # Texte
        self.difficulty_text = QtWidgets.QPlainTextEdit(Dialog)
        self.difficulty_text.setGeometry(QtCore.QRect(40, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.difficulty_text.setFont(font)
        self.difficulty_text.setAutoFillBackground(True)
        self.difficulty_text.setObjectName("difficulty_text")
        
        # Choix difficulté
        self.difficulty_box_choice = QtWidgets.QComboBox(Dialog)
        self.difficulty_box_choice.setGeometry(QtCore.QRect(140, 90, 200, 22))
        self.difficulty_box_choice.setObjectName("difficulty_box_choice")
        self.difficulty_box_choice.addItems(["Facile","Moyen", "Difficile"])
        
        # Bouton valider
        self.button_validate_difficulty = QtWidgets.QPushButton(Dialog)
        self.button_validate_difficulty.setGeometry(QtCore.QRect(300, 90, 51, 23))
        self.button_validate_difficulty.setObjectName("button_validate_difficulty")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_text.setPlainText(_translate("Dialog", "Minesweeper Game"))
        self.difficulty_text.setPlainText(_translate("Dialog", "Difficulté :"))
        self.button_validate_difficulty.setText(_translate("Dialog", "OK"))




class Window(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.grille_obj = None
        self.button_validate_difficulty.clicked.connect(self.start_game)
        
        
    def start_game(self):
        difficulte = self.difficulty_box_choice.currentIndex()
        self.grille_obj = Grille(difficulte)
        
        for i in reversed(range(self.grid.count())):
            widget = self.grid.itemAt(i).widget()
            if widget is not None:
                widget.deleteLater()
                
                
        for i in range(self.grille_obj.taille[0]):
            for j in range(self.grille_obj.taille[1]):
                case = QtWidgets.QPushButton("")
                case.setFixedSize(35, 35)
                case.setStyleSheet("background-color: lightgray;")
                case.clicked.connect(lambda _, x = i, y = j: self.handle_left_click(x, y))
                case.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
                case.customContextMenuRequested.connect(lambda _, x = i, y = j: self.handle_right_click(x, y))
                self.grid.addWidget(case, i, j)
                
    def handle_left_click(self, x, y):
        case = self.grille_obj.grille[x, y]
        case.decouvrir()
        self.update_cases()
        
    def handle_right_click(self, x, y):
        case = self.grille_obj.grille[x, y] 
        case.ajouter_drapeau()
        self.update_cases()
        
    def update_cases(self):
        for i in range(self.grille_obj.taille[0]):
            for j in range(self.grille_obj.taille[1]):
                bouton = self.grid.itemAtPosition(i, j).widget()
                case = self.grille_obj.grille[i, j]
                
                if case.drapeau == 1:
                    bouton.setText("D")
                elif not case.decouverte:
                    bouton.setText("")
                elif isinstance(case, CaseBombe):
                    bouton.setText("BOUM")
                elif case.nbr_bombes_voisines > 0:
                    bouton.setText(str(case.nbr_bombes_voisines))
                else :
                    bouton.setText("")
        
    
    
if __name__=="__main__":
    app = QtWidgets.QApplication([])
    window = Window()
    window.show()
    sys.exit(app.exec())
        
        